config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  scope "(:locale)", locale: /en|ru/ do
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    root to: 'users#index', as: 'users'

    resources :users

    resources :images

    scope ':username' do
      root to: 'categories#index', as: 'main_page'

      resources :categories, only: [:edit, :update, :new, :create, :destroy]

      resources :categories, path: '', only: [:index, :show] do
        resources :posts, path: ''
      end


    end
  end

  get '*unmatched_route', to: 'application#not_found'
  # match "/404", :to => "errors#not_found", :via => :all
  # match "/500", :to => "errors#internal_server_error", :via => :all
  # match "/403", :to => "errors#forbidden", :via => :all
  # match "/422", :to => "errors#unprocessable_entity", :via => :all
  # match "/413", :to => "errors#request_entity_too_large", :via => :all
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: true }, exclusion: { in: ["en"],
                                                                                                               message: "%{value} is reserved." }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 200 }, format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, :on => :create

  has_many :categories

  has_and_belongs_to_many :images

  attr_accessor :file, :file_cache, :current_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    authorize! :create, User
    @user = User.new
    @action = :create
    @password_correct = true
    render :new_and_edit
  end

  def create
    authorize! :create, User
    @user = User.create(user_params)
    @user.member = true
    @password_correct = true
    image = Image.create(file: user_params[:file])
    if image.valid?
      @user.images << image
    end

    if @user.save
      params[:id] = @user.id
      @action = :update
      render :new_and_edit, :flash => { :success => t('user_created') }
    else
      @action = :create
      render :new_and_edit
    end
  end

  def show
  end

  def edit
    @user = User.find(params[:id])
    authorize! :update, @user
    @action = :update
    @password_correct = true
    render :new_and_edit
  end

  def update
    @user = User.find(params[:id])
    authorize! :update, @user
    if user_params[:file].present?
      @user.images = []
      @user.images << Image.new(file: user_params[:file])
      @user.images[0].save
    end
    @user.name = user_params[:name]
    @user.email = user_params[:email]
    @user.custom_css = user_params[:custom_css]
    @user.member = true
    @password_correct = true
    if params[:password].present?
      if @user.authenticate(params[:current_password]) == false
        @password_correct = false
      else
        @user.update_attributes(password: params[:password], password_confirmation: params[:password_confirmation])
      end
    end
    if @user.save and @user.images[0].save and @password_correct
      @action = :update
      render :new_and_edit, :flash => { :success => t('user_modified') }
    else
      @action = :update
      render :new_and_edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    authorize! :destroy, @user
    delete_user = true
    if @user.categories.any?
      delete_user = false
    end
    if delete_user
      @user.delete
      redirect_to users_path, :flash => { :success => t('user_deleted') }
    else
      redirect_to users_path, :flash => { :error => t('cannot_delete_user') }
    end
  end

  private

  def user_params
    params.require(:user).permit(:file, :file_cache, :name, :email, :custom_css, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="users">
  <div class="slide">
    <table>
      <% @users.each do |u| %>
        <tr><td>
            <div class="user">
              <div class="avatar">
                <% if u.images.present? and u.images[0].file.present? %>
                  <%= link_to(image_tag(u.images[0].file.url, class:"avatar_image"), main_page_path(u.name)) %>
                <% end %>
              </div>
              <div class="username">
                <%= link_to u.name, main_page_path(u.name), class:"username_link" %>
              </div>
              <% if can? :update, u %>
                <div class="edit_links">
                  <%= link_to t('edit'), edit_user_path(u.id), class:"edit_link" %>
                  <%= link_to t('delete'), user_path(u.id), method: :delete, data: { confirm: t('delete_user_confirmation') }, class:"edit_link" %>
                </div>
              <% end %>
            </div>
            <br>
        </td></tr>
      <% end %>
      <% if can? :create, User %>
        <tr><td>
            <div class="new_user"><%= link_to t('new_user'), new_user_path, class:"new_user_link" %></div>
        </td></tr>
      <% end %>
    </table>
  </div>
</div>

app/views/users/new_and_edit.html.erb
<div class="new_and_edit">

  <h2><%= @action == :update ? t('updating_user') : t('creating_user') %></h2>
  <div class="table_div">
  <table>
    <% if @user.errors.any? or !@password_correct %>
        <tr><td>
        <div class="errors">
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
            <% unless @password_correct %>
              <li><%= t('wrong_password') %></li>
            <% end %>
          </ul>
        </div>
        </td></tr>
    <% end %>


    <tr><td>
    <% p "HERE", @user.id, @action %>
    <%= form_for @user, action: @action, html: { multipart: true }, method: @action == :update ? :PATCH : :POST do |f| %>
        <div class="params">
          <table>
            <tr>
              <td><%= t('username') %></td><td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <td><%= t('email') %></td><td><%= f.text_field :email %></td>
            </tr>
            <tr>
              <td><%= t('CSS') %></td><td><%= f.text_area :custom_css %></td>
            </tr>
            <% if @action == :update %>
              <tr>
                <td><%= t('old_password') %></td><td><%= f.password_field :current_password %></td>
              </tr>
            <% end %>
            <tr>
              <td><%= t('new_password') %></td><td><%= f.password_field :password %></td>
            </tr>
            <tr>
              <td><%= t('password_confirmation') %></td><td><%= f.password_field :password_confirmation %></td>
            </tr>
            <tr>
              <td><%= t('avatar') %></td>
              <td>
                <% if @user.images.present? and @user.images[0].file.present? %>
                    <%= image_tag @user.images[0].file.url %>
                <% end %>
                <%= f.file_field :file %>
                <%= f.hidden_field :file_cache %>
              </td>
            </tr>
            <tr>
              <td><%= f.submit @action == :update ? t('update') : t('create') %>  <%= submit_tag t('back'), :type => 'button', class:"back_button" %></td><td></td>
            </tr>
          </table>
        </div>
    <% end %>
    </td></tr>
  </table>
  </div>
</div>

app/views/users/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>