config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  scope "(:locale)", locale: /en|ru/ do
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    root to: 'users#index', as: 'users'

    resources :users

    resources :images

    scope ':username' do
      root to: 'categories#index', as: 'main_page'

      resources :categories, only: [:edit, :update, :new, :create, :destroy]

      resources :categories, path: '', only: [:index, :show] do
        resources :posts, path: ''
      end


    end
  end

  get '*unmatched_route', to: 'application#not_found'
  # match "/404", :to => "errors#not_found", :via => :all
  # match "/500", :to => "errors#internal_server_error", :via => :all
  # match "/403", :to => "errors#forbidden", :via => :all
  # match "/422", :to => "errors#unprocessable_entity", :via => :all
  # match "/413", :to => "errors#request_entity_too_large", :via => :all
end

app/models/post.rb
class Post < ApplicationRecord
  validate :category_is_not_header
  validates :content, :created_at, presence: true
  belongs_to :category
  default_scope { order(priority: :desc, created_at: :desc) }

  def category_is_not_header
    if category.destination == "header"
      errors.add(:category, I18n.t('category_should_not_be_header'))
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @username = params[:username]
    @category = Category.find_by(path: params[:category_id])
    unless @category.present?
      render :file => 'public/404.html', :status => :not_found, :layout => false
      return
    end
    @posts = @category.posts.paginate(:page => params[:page], :per_page => 30)
    @users = User.all
  end

  def new
    authorize! :create, Post
    @username = params[:username]
    @category = Category.find_by(path: params[:category_id])
    authorize! :update, @category
    @post = Post.new
    @action = :create
    @users = User.all
    render :new_and_edit
  end

  def create
    authorize! :create, Post
    @users = User.all
    @username = params[:username]
    @category = Category.find_by(path: params[:category_id])
    authorize! :update, @category
    @post = @category.posts.create(post_params)
    if @post.created_at.nil?
      @post.created_at = DateTime.now
    end
    if @post.save
      redirect_to category_posts_path(params[:username], @category.path), :flash => { :success => t('post_created') }
    else
      @action = :create
      render :new_and_edit
    end
  end

  def show
    @users = User.all
    @username = params[:username]
    @post = Post.find(params[:id])
    @category = @post.category
  end

  def edit
    @username = params[:username]
    @users = User.all
    @post = Post.find(params[:id])
    authorize! :update, @post
    @category = @post.category
    @action = :update
    render :new_and_edit
  end

  def update
    @users = User.all
    @username = params[:username]
    @category = Category.find_by(path: params[:category_id])
    @post = Post.find(params[:id])
    authorize! :update, @post
    if @post.update(post_params)
      redirect_to category_post_path(params[:username], @post.category.name, @post), :flash => { :success => t('post_modified') }
    else
      @action = :update
      render :new_and_edit
    end
  end

  def destroy
    @username = params[:username]
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    @post.delete
    redirect_to category_posts_path(@username, @post.category.path), :flash => { :success => t('post_deleted') }
  end

  private

  def post_params
    params.require(:post).permit(:name, :content, :english_name, :english_content, :priority, :created_at)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="main_block">
  <div class="contents">
    <% if @category.present? %>
      <% if can? :manage, @category %>
        <div>
        <%= link_to t('edit_category'), edit_category_path(@username, @category.id), class:"edit_category_link" %>
        <%= link_to t('delete_category'), category_path(@username, @category.id), method: :delete, data: { confirm: t('confirm_category_delete') }, class:"edit_category_link" %>
        </div>
      <% end %>
      <div class="welcome_text">
        <% if I18n.locale == :en and @category.english_description.present? %>
          <%=  sanitize(BlueCloth.new(@category.english_description).to_html) %>
        <% else %>
          <%=  sanitize(BlueCloth.new(@category.description).to_html) %>
        <% end %>
      </div>
    <% end %>
    <div class="posts">
      <% if can? :manage, @category and can? :create, Post and @category.destination != "header" %>
        <div><%= link_to t('new_post'), new_category_post_path(@username, @category.path), class:"new_post_link" %></div>
        <br>
        <br>
      <% end %>
      <% @posts.each do |p| %>
          <div class="datetime">
            <%= link_to (p.created_at.to_time).strftime("%Y-%m-%d %H:%M"), category_post_path(@username, p.category.path, p.id), class:"datetime_link" %>
          </div>
          <div class="post_name">
            <% post_name = '' %>
            <% if I18n.locale == :en and p.english_name.present? %>
                <% post_name = p.english_name %>
            <% else %>
                <% post_name = p.name %>
            <% end %>
            <%= link_to post_name, category_post_path(@username, p.category.path, p.id), class:"post_name_link" %>
          </div>
          <% if can? :manage, p %>
            <div class="edit_links">
              <%= link_to t('edit'), edit_category_post_path(@username, p.category.path, p.id), class:"edit_link" %>
              <%= link_to t('delete'), category_post_path(@username, p.category.path, p.id), method: :delete, data: { confirm: t('confirm_post_delete') }, class:"edit_link" %>
            </div>
          <% end %>
          <div class="content">
            <% if I18n.locale == :en and p.english_content.present? %>
                <%=  sanitize(BlueCloth.new(p.english_content).to_html) %>
            <% else %>
                <%=  sanitize(BlueCloth.new(p.content).to_html) %>
            <% end %>
          </div>
          <br>
      <% end %>
      <%= will_paginate @posts, :previous_label => t("previous"), :next_label => t("next")  %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>Post#new</h1>
<p>Find me in app/views/post/new.html.erb</p>

app/views/posts/new_and_edit.html.erb
<div class="main_block">
  <div class="new_and_edit">

    <div><%= link_to @category.name, category_posts_path(@username, @category.path), class:"category_link" %></div>

<h2><%= @action == :update ? t('updating_post') : t('creating_post') %></h2>
    <div class="table_div">
      <table>
<% if @post.errors.any? %>
  <tr><td>
    <div class="errors">
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </td></tr>
<% end %>

        <tr><td>
<%= form_for @post, url: {action: @action}, html: { multipart: true }, method: @action == :update ? :PATCH : :POST  do |f| %>
    <table>
      <tr>
        <td><%= t('post_name') %></td><td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <td><%= t('created_at') %></td><td><%= f.text_field :created_at %></td>
      </tr>
      <tr>
        <td><%= t('priority') %></td><td><%= f.text_field :priority, type: "number", max: 2147483647  %></td>
      </tr>
      <tr>
        <td><%= t('post_content') %></td><td><%= f.text_area :content %></td>
      </tr>
      <tr>
        <td><%= t('post_english_name') %></td><td><%= f.text_field :english_name %></td>
      </tr>
      <tr>
        <td><%= t('post_english_content') %></td><td><%= f.text_area :english_content %></td>
      </tr>
      <tr>
        <td><%= f.submit @action == :update ? t('update') : t('create') %></td><td></td>
      </tr>
    </table>
<% end %>
        </td></tr>
    </table>
  </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main_block">
  <div class="contents">
    <div class="posts">
      <% name = '' %>
      <% if I18n.locale == :en and @category.english_name.present? %>
          <% name = @category.english_name.split("\\n").join(" ") %>
      <% else %>
          <% name = @category.name.split("\\n").join(" ") %>
      <% end %>
      <div class="category_link_div"><%= link_to name, category_posts_path(@username, @category.path), class:"category_link" %></div>

      <div class="datetime">
        <%= @post.created_at.to_time.strftime("%Y-%m-%d %H:%M") %>
      </div>
      <div class="post_name">
        <% post_name = '' %>
        <% if I18n.locale == :en and @post.english_name.present? %>
            <% post_name = @post.english_name %>
        <% else %>
            <% post_name = @post.name %>
        <% end %>
        <%= link_to post_name, category_post_path(@username, @post.category.name, @post.id), class:"post_name_link" %>
      </div>
      <% if can? :manage, @post %>
        <div class="edit_links">
          <%= link_to t('edit'), edit_category_post_path(@username, @post.category.name, @post.id), class:"edit_link" %>
          <%= link_to t('delete'), category_post_path(@username, @post.category.name, @post.id), method: :delete, data: { confirm: t('confirm_post_delete') }, class:"edit_link" %>
        </div>
      <% end %>
      <div class="content">
        <% if I18n.locale == :en and @post.english_content.present? %>
          <%=  sanitize(BlueCloth.new(@post.english_content).to_html) %>
        <% else %>
          <%=  sanitize(BlueCloth.new(@post.content).to_html) %>
        <% end %>
      </div>
      <br>

    </div>
  </div>
</div>