config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  scope "(:locale)", locale: /en|ru/ do
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    root to: 'users#index', as: 'users'

    resources :users

    resources :images

    scope ':username' do
      root to: 'categories#index', as: 'main_page'

      resources :categories, only: [:edit, :update, :new, :create, :destroy]

      resources :categories, path: '', only: [:index, :show] do
        resources :posts, path: ''
      end


    end
  end

  get '*unmatched_route', to: 'application#not_found'
  # match "/404", :to => "errors#not_found", :via => :all
  # match "/500", :to => "errors#internal_server_error", :via => :all
  # match "/403", :to => "errors#forbidden", :via => :all
  # match "/422", :to => "errors#unprocessable_entity", :via => :all
  # match "/413", :to => "errors#request_entity_too_large", :via => :all
end

app/views/layouts/_header.html.erb
<div class="outer">
  <div class="second">
    <div class="header">
      <div class="link_div"><%= link_to t('home'), users_path, class:"menu_link" %></div>
      <% @users.each do |u| %>
          <div class="link_div">
            <% if u.name == @username %>
                <%= link_to u.name, main_page_path(u.name), class:"menu_link username_link", id:u.name %>
            <% else %>
                <%= link_to u.name, main_page_path(u.name), class:"menu_link", id:u.name %>
            <% end %>
          </div>
      <% end %>
      <% if params[:locale] == "en" %>
          <%= link_to 'Русский', url_for( :locale => nil ), class:"menu_link" %>
      <% else %>
          <%= link_to 'English', url_for( :locale => 'en' ), class:"menu_link" %>
      <% end %>
      <% if current_user.present? %>
          <div class="link_div"><%= link_to t('edit_images'), images_path, class:"menu_link" %></div>
          <div class="link_div"><%= t('you_are_logged_in_as') %><b><%= current_user.name %></b></div>
          <div class="link_div"><%= link_to t('logout'), logout_path, method: :delete, class:"menu_link" %></div>
      <% end %>
    </div>

    <% if flash.count > 0 %>
      <div class="flash_div">
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</div>
<div class="up"><a class="up_link"><%= t('up') %></a></div>

app/views/layouts/_header_with_image.html.erb
<div class="welcome_image_area">

    <div class="typewrite_div">
      <% if @header_category.present? or @category.present? %>
        <% c = @header_category.present? ? @header_category : @category %>
        <% if c.present? and c.no_typewrite %>
          <a class="no-typewrite" style="color:<%= c ? c.color : 'white' %>;">
            <% name = '' %>
            <% if I18n.locale == :en and c.english_name.present? %>
                <% name = c.english_name %>
            <% elsif c.name.present? %>
                <% name = c.name %>
            <% end %>
            <%= name.split("\\n").join(", ") %>
          </a>
        <% elsif c.present? %>
          <a class="typewrite" data-period="1000" data-type='[
            <% name = '' %>
            <% if I18n.locale == :en and c.english_name.present? %>
              <% name = c.english_name %>
            <% elsif c.name.present? %>
              <% name = c.name %>
            <% end %>
            <%= name.split("\\n").map{|x| "\"" + x + "\"" }.join(", ") %>

           ]'
           style="color:<%= c and c.color ? c.color : 'white' %>;"
          >
          <span class="wrap"></span>
          </a>
        <% end %>
      <% end %>
    </div>
  <% c = @header_category.present? ? @header_category : @category %>
  <% if c.present? and c.black_arrow? %>
    <div class="arrow"><img src="/images/black_arrow.png" width="100" alt="black_arrow"></div>
  <% else %>
    <div class="arrow"><img src="/images/arrow.png" width="100" alt="arrow"></div>
  <% end %>
</div>

<%= render partial: "layouts/header" %>

app/views/layouts/_very_header.html.erb
<title>
  <% if @header_category.present? or @category.present? %>
      <% c = @header_category.present? ? @header_category : @category %>
      <% if c.present? and c.user.present? %>
          <%= c.user.name %>
      <% end %>
      <% if c.english_name.present? and I18n.locale == :en and c.english_name != c.user.name %>
          <%= " | " + c.english_name.split("\\n").join(" ") %>
      <% elsif c.name.present? and c.name != c.user.name %>
          <%= " | " + c.name.split("\\n").join(" ") %>
      <% end %>
  <% end %>

</title>
<%= csrf_meta_tags %>
<%= favicon_link_tag %>

<%= stylesheet_link_tag    'categories', media: 'all' %>
<%= stylesheet_link_tag    'highlight', media: 'all' %>
<%= javascript_include_tag 'application' %>

<% if @header_category.present? or @category.present? %>
    <% c = @header_category.present? ? @header_category : @category %>
    <% unless c.images[0].present? %>
        <% if c.present? and c.user.present? and c.user.categories.present? %>
            <% c = c.user.categories.where(destination: "header")[0] %>
        <% end %>
    <% end %>
    <style type="text/css">
      html {
      <% if c.present? and c.images.present? and c.images[0].present? %>
        background: url("<%= c.images[0].file.url %>") no-repeat center center fixed black;
      <% end %>
        background-size: cover !important;
      }
    </style>
<% end %>

<% if @users.present? and @users.where(name: @username)[0].custom_css.present? %>
    <style type="text/css">
      <%= sanitize(@users.where(name: @username)[0].custom_css) %>
    </style>
<% end %>

app/views/layouts/_yandex_metrika.html.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
      try {
        w.yaCounter983836 = new Ya.Metrika({
          id:983836,
          clickmap:true,
          trackLinks:true,
          accurateTrackBounce:true
        });
      } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = "https://mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
      d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/983836" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html <% if I18n.locale == :en %> lang="en" <% else %> lang="ru" <% end %> >
<head>
  <title>Idzaaus</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>

<%= yield %>
</body>
</html>

app/views/layouts/categories.html.erb
<!DOCTYPE html>
<html <% if I18n.locale == :en %> lang="en" <% else %> lang="ru" <% end %> >
<head>
  <%= render partial: "layouts/very_header" %>
</head>

<body>
<%= render partial: "layouts/yandex_metrika" %>
<%= render partial: "layouts/header_with_image" %>

</body>
</html>

app/views/layouts/errors.html.erb
<!DOCTYPE html>
<html <% if I18n.locale == :en %> lang="en" <% else %> lang="ru" <% end %> >
<head>
  <title>Idzaaus</title>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    'users', media: 'all' %>
  <%= javascript_include_tag 'application' %>

</head>

<body>
<% render partial: "layouts/yandex_metrika" %>
<img class="bg" src="/images/main_background.jpg">

<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/layouts/images.html.erb
<!DOCTYPE html>
<html <% if I18n.locale == :en %> lang="en" <% else %> lang="ru" <% end %> >
<head>
  <title>Idzaaus</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'images', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= render partial: "layouts/yandex_metrika" %>
</head>

<body>
<%= render partial: "layouts/yandex_metrika" %>
<%= render partial: "layouts/header" %>
</div>
</body>

app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html <% if I18n.locale == :en %> lang="en" <% else %> lang="ru" <% end %> >
<head>
  <%= render partial: "layouts/very_header" %>
</head>

<body>

<% render partial: "layouts/yandex_metrika" %>
<%= render partial: "layouts/header_with_image" %>

</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html <% if I18n.locale == :en %> lang="en" <% else %> lang="ru" <% end %> >
<head>
  <title>Idzaaus</title>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    'users', media: 'all' %>
  <%= javascript_include_tag 'application' %>

</head>


<body class="preload">
<% render partial: "layouts/yandex_metrika" %>
<img class="bg" src="/images/main_background.jpg" alt="background">

<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= yield %>

</body>
</html>